name: Validate sample queries
on:
  push:
    paths:
      - sample-queries/sample-queries.json
      - scripts/**
      - tests/**
      - package.json
      - package-lock.json
  pull_request:
    paths:
      - sample-queries/sample-queries.json
      - scripts/**
      - tests/**
      - package.json
      - package-lock.json

jobs:
  validate-json-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate json schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /tests/samples.schema.json
          INPUT_JSONS: /sample-queries/sample-queries.json

  test:
    runs-on: ubuntu-latest
    needs: validate-json-schema
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Run test
        run: npm run test
